# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAyNY2cX-hNV_KfhS6ZwQgI6g8SxU3UG
"""

!pip install streamlit plotly -q

import urllib
print("Sua senha para o site é:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(page_title="Dashboard Olist", page_icon="🛒", layout="wide")
# st.title("🛒 E-commerce Olist - App de Dados Interativo")
# 
# aba1, aba2 = st.tabs(["📊 Análise de Dados", "🤖 GenAI - Gerador de Vendas (Bônus)"])
# 
# @st.cache_data
# def load_data():
#     caminho_correto = '/content/olist_orders_dataset.csv'
#     try:
#         df = pd.read_csv(caminho_correto)
#         df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
#         return df
#     except Exception as e:
#         st.error("⚠️ O ficheiro 'olist_orders_dataset.csv' não foi encontrado na pasta. Por favor, faça o upload novamente no Colab.")
#         return pd.DataFrame()
# 
# df = load_data()
# 
# with aba1:
#     if not df.empty:
#         st.sidebar.header("Filtros Interativos")
#         status_lista = df['order_status'].unique().tolist()
#         status_selecionado = st.sidebar.multiselect("Selecione o Status:", options=status_lista, default=status_lista)
#         df_filtrado = df[df['order_status'].isin(status_selecionado)]
# 
#         st.subheader("Métricas Principais")
#         col1, col2 = st.columns(2)
#         col1.metric(label="Total de Pedidos", value=f"{len(df_filtrado):,}".replace(",", "."))
#         if not df_filtrado.empty:
#             status_mais_comum = df_filtrado['order_status'].mode()[0]
#             col2.metric(label="Status Mais Frequente", value=status_mais_comum.capitalize())
# 
#         st.markdown("---")
# 
#         st.subheader("Evolução de Pedidos por Dia")
#         df_filtrado['data'] = df_filtrado['order_purchase_timestamp'].dt.date
#         pedidos_por_dia = df_filtrado.groupby('data').size().reset_index(name='quantidade')
#         fig_linha = px.line(
#             pedidos_por_dia, x='data', y='quantidade',
#             labels={'data': 'Data da Compra', 'quantidade': 'Quantidade de Pedidos'}
#         )
#         st.plotly_chart(fig_linha, use_container_width=True)
# 
#         st.subheader("Análises Detalhadas")
#         col_grafico1, col_grafico2 = st.columns(2)
# 
#         with col_grafico1:
#             status_contagem = df_filtrado['order_status'].value_counts().reset_index()
#             status_contagem.columns = ['status', 'quantidade']
#             fig_pizza = px.pie(
#                 status_contagem, values='quantidade', names='status',
#                 title='Proporção por Status do Pedido',
#                 hole=0.4
#             )
#             st.plotly_chart(fig_pizza, use_container_width=True)
# 
#         with col_grafico2:
#             df_filtrado['dia_semana_num'] = df_filtrado['order_purchase_timestamp'].dt.dayofweek
#             dias_map = {0: 'Segunda', 1: 'Terça', 2: 'Quarta', 3: 'Quinta', 4: 'Sexta', 5: 'Sábado', 6: 'Domingo'}
#             df_filtrado['dia_semana'] = df_filtrado['dia_semana_num'].map(dias_map)
# 
#             pedidos_dia_semana = df_filtrado.groupby(['dia_semana_num', 'dia_semana']).size().reset_index(name='quantidade')
#             pedidos_dia_semana = pedidos_dia_semana.sort_values('dia_semana_num')
# 
#             fig_barras = px.bar(
#                 pedidos_dia_semana, x='dia_semana', y='quantidade',
#                 title='Volume de Pedidos por Dia da Semana',
#                 labels={'dia_semana': 'Dia da Semana', 'quantidade': 'Quantidade'},
#                 color='quantidade',
#                 color_continuous_scale='Blues'
#             )
#             st.plotly_chart(fig_barras, use_container_width=True)
# 
# with aba2:
#     st.header("✨ Assistente de Vendas com Inteligência Artificial")
#     st.markdown("Utilização de GenAI (LLMs e DALL-E) para impulsionar a conversão de produtos.")
# 
#     col_img, col_txt = st.columns([1, 2])
# 
#     with col_img:
#         try:
#             st.image("produto_ia.jpg", caption="Imagem gerada por IA (DALL-E 3)")
#         except:
#             st.info("Faça o upload da imagem 'produto_ia.jpg' na mesma pasta para visualizar.")
# 
#     with col_txt:
#         st.subheader("Headphones Premium (Exemplo de Geração)")
#         st.write("**Prompt Utilizado no DALL-E:**")
#         st.code("Uma fotografia de estúdio de alta qualidade de uns auscultadores (headphones) Bluetooth modernos e minimalistas, cor preto mate com detalhes em ouro rosa. Iluminação dramática, fundo escuro. Estilo de publicidade comercial premium para e-commerce, 8k, hiper-realista.", language="text")
# 
#         st.write("**Copywriting Gerado por LLM para Vendas:**")
#         st.success("Eleve a sua experiência sonora ao próximo nível. Com cancelamento de ruído ativo e design ergonómico, estes auscultadores foram desenhados para quem não aceita menos do que a perfeição. Compre agora e receba em 24h!")

!streamlit run app.py & npx localtunnel --port 8501

!pip install pyspark -q

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, year, month, to_timestamp

print("Iniciando o Pipeline de Dados (ETL) com Apache Spark...\n")

spark = SparkSession.builder.appName("OlistETL").getOrCreate()

df_bruto = spark.read.csv('/content/olist_orders_dataset.csv', header=True, inferSchema=True)

df_transformado = df_bruto.withColumn("data_compra", to_timestamp(col("order_purchase_timestamp"))) \
                          .withColumn("ano_compra", year(col("data_compra"))) \
                          .withColumn("mes_compra", month(col("data_compra"))) \
                          .filter(col("order_status") == 'delivered')

print("Transformação concluída! Amostra dos dados modelados prontos para análise:")
df_transformado.select("order_id", "order_status", "data_compra", "ano_compra", "mes_compra").show(5, truncate=False)

!pip install great_expectations==0.15.50 -q

import great_expectations as ge
import pandas as pd

print("🚀 A iniciar a validação de Data Quality com Great Expectations...\n")

# Lê com pandas e converte
df_pandas = pd.read_csv('/content/olist_orders_dataset.csv')
df = ge.from_pandas(df_pandas)

teste_nulos = df.expect_column_values_to_not_be_null('order_id')
print(f"Teste 1 (order_id sem nulos): {' PASSOU' if teste_nulos['success'] else ' FALHOU'}")

status_oficiais = ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'created', 'approved']
teste_status = df.expect_column_values_to_be_in_set('order_status', status_oficiais)
print(f"Teste 2 (order_status contém valores válidos): {' PASSOU' if teste_status['success'] else ' FALHOU'}")

teste_tamanho_id = df.expect_column_value_lengths_to_equal('customer_id', 32)
print(f"Teste 3 (customer_id com 32 caracteres): {' PASSOU' if teste_tamanho_id['success'] else ' FALHOU'}")

# Instalar a biblioteca de IA da Hugging Face
!pip install transformers -q

import pandas as pd
from transformers import pipeline
from IPython.display import display

analisador = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

comentarios = [
    "Adorei o produto, chegou super rápido e bem embalado!",
    "Péssimo. A caixa veio rasgada e faltavam peças. Quero o meu dinheiro de volta.",
    "Produto razoável. Pelo preço vale a pena, mas a qualidade não é a melhor.",
    "Ainda não recebi o meu pedido, estou muito chateado com a demora.",
    "Excelente atendimento da loja, recomendo a todos."
]

df_reviews = pd.DataFrame({'texto_desestruturado': comentarios})

resultados = analisador(comentarios)

df_reviews['feature_sentimento_ia'] = [res['label'] for res in resultados]
df_reviews['confianca_do_modelo'] = [round(res['score'], 2) for res in resultados]

display(df_reviews)