# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAyNY2cX-hNV_KfhS6ZwQgI6g8SxU3UG
"""

!pip install streamlit plotly -q

import urllib
print("Sua senha para o site é:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(page_title="Dashboard Olist", page_icon="🛒", layout="wide")
# st.title("🛒 E-commerce Olist - App de Dados Interativo")
# 
# @st.cache_data
# def load_data():
#     # Caminho padrão do Colab atualizado
#     caminho_correto = '/content/olist_orders_dataset.csv'
#     try:
#         df = pd.read_csv(caminho_correto)
#         df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
#         return df
#     except Exception as e:
#         st.error(f"⚠️ Erro ao carregar: {e}")
#         return pd.DataFrame()
# 
# df = load_data()
# 
# if not df.empty:
#     st.sidebar.header("Filtros Interativos")
#     status_lista = df['order_status'].unique().tolist()
#     status_selecionado = st.sidebar.multiselect(
#         "Selecione o Status do Pedido:",
#         options=status_lista,
#         default=status_lista
#     )
# 
#     df_filtrado = df[df['order_status'].isin(status_selecionado)]
# 
#     st.subheader("Métricas Principais")
#     col1, col2 = st.columns(2)
#     col1.metric(label="Total de Pedidos", value=f"{len(df_filtrado):,}".replace(",", "."))
# 
#     if not df_filtrado.empty:
#         status_mais_comum = df_filtrado['order_status'].mode()[0]
#         col2.metric(label="Status Mais Frequente", value=status_mais_comum.capitalize())
# 
#     st.markdown("---")
# 
#     st.subheader("Evolução de Pedidos por Dia")
#     df_filtrado['data'] = df_filtrado['order_purchase_timestamp'].dt.date
#     pedidos_por_dia = df_filtrado.groupby('data').size().reset_index(name='quantidade')
# 
#     fig_linha = px.line(
#         pedidos_por_dia, x='data', y='quantidade',
#         labels={'data': 'Data da Compra', 'quantidade': 'Quantidade de Pedidos'}
#     )
#     st.plotly_chart(fig_linha, use_container_width=True)
# 
#     st.subheader("Análises Detalhadas")
#     col_grafico1, col_grafico2 = st.columns(2)
# 
#     with col_grafico1:
#         status_contagem = df_filtrado['order_status'].value_counts().reset_index()
#         status_contagem.columns = ['status', 'quantidade']
#         fig_pizza = px.pie(
#             status_contagem, values='quantidade', names='status',
#             title='Proporção por Status do Pedido',
#             hole=0.4
#         )
#         st.plotly_chart(fig_pizza, use_container_width=True)
# 
#     with col_grafico2:
#         df_filtrado['dia_semana_num'] = df_filtrado['order_purchase_timestamp'].dt.dayofweek
#         dias_map = {0: 'Segunda', 1: 'Terça', 2: 'Quarta', 3: 'Quinta', 4: 'Sexta', 5: 'Sábado', 6: 'Domingo'}
#         df_filtrado['dia_semana'] = df_filtrado['dia_semana_num'].map(dias_map)
# 
#         pedidos_dia_semana = df_filtrado.groupby(['dia_semana_num', 'dia_semana']).size().reset_index(name='quantidade')
#         pedidos_dia_semana = pedidos_dia_semana.sort_values('dia_semana_num')
# 
#         fig_barras = px.bar(
#             pedidos_dia_semana, x='dia_semana', y='quantidade',
#             title='Volume de Pedidos por Dia da Semana',
#             labels={'dia_semana': 'Dia da Semana', 'quantidade': 'Quantidade'},
#             color='quantidade',
#             color_continuous_scale='Blues'
#         )
#         st.plotly_chart(fig_barras, use_container_width=True)

!streamlit run app.py & npx localtunnel --port 8501